<?xml version="1.0" encoding="utf-8"?><Database Name="DACN" Class="HutechEduDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=QCUONG\SQLEXPRESS;Initial Catalog=DACN;Integrated Security=True" SettingsObjectName="Edu_Hutech.Properties.Settings" SettingsPropertyName="DACNConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CanBo_HuongDan" Member="CanBo_HuongDans">
    <Type Name="CanBo_HuongDan">
      <Column Name="MaGV" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenGV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="CanBo_HuongDan_PhieuDangKy_DeTai_NCKH" Member="PhieuDangKy_DeTai_NCKHs" ThisKey="MaGV" OtherKey="Ma_GVHD2" Type="PhieuDangKy_DeTai_NCKH" />
      <Association Name="CanBo_HuongDan_PhieuDangKy_DeTai_NCKH1" Member="PhieuDangKy_DeTai_NCKHs1" ThisKey="MaGV" OtherKey="Ma_GVHD1" Type="PhieuDangKy_DeTai_NCKH" />
    </Type>
  </Table>
  <Table Name="dbo.TieuChuan_LHTT" Member="TieuChuan_LHTTs">
    <Type Name="TieuChuan_LHTT">
      <Column Name="MaCap" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="DIem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ma_TC" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CapDanhHieu_TieuChuan_LHTT" Member="CapDanhHieu" ThisKey="MaCap" OtherKey="MaCap" Type="CapDanhHieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CapDanhHieu" Member="CapDanhHieus">
    <Type Name="CapDanhHieu">
      <Column Name="MaCap" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCap" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="CapDanhHieu_TieuChuan_LHTT" Member="TieuChuan_LHTTs" ThisKey="MaCap" OtherKey="MaCap" Type="TieuChuan_LHTT" />
      <Association Name="CapDanhHieu_KQ_DeTai_NCKH" Member="KQ_DeTai_NCKHs" ThisKey="MaCap" OtherKey="MaCap" Type="KQ_DeTai_NCKH" />
      <Association Name="CapDanhHieu_PhieuDangKy_SV5T" Member="PhieuDangKy_SV5Ts" ThisKey="MaCap" OtherKey="MaCap" Type="PhieuDangKy_SV5T" />
    </Type>
  </Table>
  <Table Name="dbo.DeTai_NCKH" Member="DeTai_NCKHs">
    <Type Name="DeTai_NCKH">
      <Column Name="MSSV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaPDK_NCKH" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="PhieuDangKy_DeTai_NCKH_DeTai_NCKH" Member="PhieuDangKy_DeTai_NCKH" ThisKey="MaPDK_NCKH" OtherKey="MaPDK_NCKH" Type="PhieuDangKy_DeTai_NCKH" IsForeignKey="true" />
      <Association Name="SinhVien_DeTai_NCKH" Member="SinhVien" ThisKey="MSSV" OtherKey="MSSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Khoa" Member="Khoas">
    <Type Name="Khoa">
      <Column Name="MaKhoa" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoa" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Khoa_Lop" Member="Lops" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="Lop" />
    </Type>
  </Table>
  <Table Name="dbo.KQ_danhgia_LHTT_SV" Member="KQ_danhgia_LHTT_SVs">
    <Type Name="KQ_danhgia_LHTT_SV">
      <Column Name="MaPDK_LHTT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ma_NDTieuChi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="KQ_danhgia_LHTT_SV_KQ_DanhGiaND_LHTT_Admin" Member="KQ_DanhGiaND_LHTT_Admins" ThisKey="MaPDK_LHTT,Ma_NDTieuChi" OtherKey="MaPDK_LHTT,Ma_NDTieuChi" Type="KQ_DanhGiaND_LHTT_Admin" />
      <Association Name="PhieuDangKy_LHTT_KQ_danhgia_LHTT_SV" Member="PhieuDangKy_LHTT" ThisKey="MaPDK_LHTT" OtherKey="MaPDK_LHTT" Type="PhieuDangKy_LHTT" IsForeignKey="true" />
      <Association Name="TieuChi_KQ_danhgia_LHTT_SV" Member="TieuChi" ThisKey="Ma_NDTieuChi" OtherKey="Ma_NDTieuChi" Type="TieuChi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KQ_danhgia_SV5T_SV" Member="KQ_danhgia_SV5T_SVs">
    <Type Name="KQ_danhgia_SV5T_SV">
      <Column Name="Ma_NDTieuChi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaPDK_SV5T" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KQ_danhgia_SV5T_SV_KQ_DanhGiaND_SV5T_Admin" Member="KQ_DanhGiaND_SV5T_Admins" ThisKey="Ma_NDTieuChi,MaPDK_SV5T" OtherKey="Ma_NDTieuChi,MaPDK_SV5T" Type="KQ_DanhGiaND_SV5T_Admin" />
      <Association Name="PhieuDangKy_SV5T_KQ_danhgia_SV5T_SV" Member="PhieuDangKy_SV5T" ThisKey="MaPDK_SV5T" OtherKey="MaPDK_SV5T" Type="PhieuDangKy_SV5T" IsForeignKey="true" />
      <Association Name="TieuChi_KQ_danhgia_SV5T_SV" Member="TieuChi" ThisKey="Ma_NDTieuChi" OtherKey="Ma_NDTieuChi" Type="TieuChi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KQ_DanhGiaND_LHTT_Admin" Member="KQ_DanhGiaND_LHTT_Admins">
    <Type Name="KQ_DanhGiaND_LHTT_Admin">
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaPDK_LHTT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ma_NDTieuChi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Diem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KQ_danhgia_LHTT_SV_KQ_DanhGiaND_LHTT_Admin" Member="KQ_danhgia_LHTT_SV" ThisKey="MaPDK_LHTT,Ma_NDTieuChi" OtherKey="MaPDK_LHTT,Ma_NDTieuChi" Type="KQ_danhgia_LHTT_SV" IsForeignKey="true" />
      <Association Name="TaiKhoan_ADMIN_KQ_DanhGiaND_LHTT_Admin" Member="TaiKhoan_ADMIN" ThisKey="TaiKhoan" OtherKey="TaiKhoan" Type="TaiKhoan_ADMIN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KQ_DanhGiaND_SV5T_Admin" Member="KQ_DanhGiaND_SV5T_Admins">
    <Type Name="KQ_DanhGiaND_SV5T_Admin">
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ma_NDTieuChi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaPDK_SV5T" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Dat" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KQ_danhgia_SV5T_SV_KQ_DanhGiaND_SV5T_Admin" Member="KQ_danhgia_SV5T_SV" ThisKey="Ma_NDTieuChi,MaPDK_SV5T" OtherKey="Ma_NDTieuChi,MaPDK_SV5T" Type="KQ_danhgia_SV5T_SV" IsForeignKey="true" />
      <Association Name="TaiKhoan_ADMIN_KQ_DanhGiaND_SV5T_Admin" Member="TaiKhoan_ADMIN" ThisKey="TaiKhoan" OtherKey="TaiKhoan" Type="TaiKhoan_ADMIN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KQ_DeTai_NCKH" Member="KQ_DeTai_NCKHs">
    <Type Name="KQ_DeTai_NCKH">
      <Column Name="MaPDK_NCKH" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCap" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KQ" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CapDanhHieu_KQ_DeTai_NCKH" Member="CapDanhHieu" ThisKey="MaCap" OtherKey="MaCap" Type="CapDanhHieu" IsForeignKey="true" />
      <Association Name="PhieuDangKy_DeTai_NCKH_KQ_DeTai_NCKH" Member="PhieuDangKy_DeTai_NCKH" ThisKey="MaPDK_NCKH" OtherKey="MaPDK_NCKH" Type="PhieuDangKy_DeTai_NCKH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lop" Member="Lops">
    <Type Name="Lop">
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhoa" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Lop_SinhVien" Member="SinhViens" ThisKey="MaLop" OtherKey="MaLop" Type="SinhVien" />
      <Association Name="Khoa_Lop" Member="Khoa" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="Khoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MinhChung" Member="MinhChungs">
    <Type Name="MinhChung">
      <Column Name="MaMinhChung" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenMInhChung" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="MinhChung_PhieuDangKy_LHTT" Member="PhieuDangKy_LHTTs" ThisKey="MaMinhChung" OtherKey="MaMinhChung" Type="PhieuDangKy_LHTT" />
      <Association Name="MinhChung_PhieuDangKy_SV5T" Member="PhieuDangKy_SV5Ts" ThisKey="MaMinhChung" OtherKey="MaMinhChung" Type="PhieuDangKy_SV5T" />
    </Type>
  </Table>
  <Table Name="dbo.PDK_BaiBao_ThamLuan_NCKH" Member="PDK_BaiBao_ThamLuan_NCKHs">
    <Type Name="PDK_BaiBao_ThamLuan_NCKH">
      <Column Name="MaPDK_BBao_TL_CKH" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenBaiBao" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MSSV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="SinhVien_PDK_BaiBao_ThamLuan_NCKH" Member="SinhVien" ThisKey="MSSV" OtherKey="MSSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanCap_TieuChi" Member="PhanCap_TieuChis">
    <Type Name="PhanCap_TieuChi">
      <Column Name="MaPhanCap" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Khoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Truong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Thanh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TrungUong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PhanLoai" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Association Name="PhanCap_TieuChi_TieuChi" Member="TieuChis" ThisKey="MaPhanCap" OtherKey="MaPhanCap" Type="TieuChi" />
      <Association Name="PhanLoai_PhanCap_TieuChi" Member="PhanLoai1" ThisKey="PhanLoai" OtherKey="PhanLoai1" Type="PhanLoai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanLoai" Member="PhanLoais">
    <Type Name="PhanLoai">
      <Column Name="PhanLoai" Member="PhanLoai1" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BatBuoc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="PhanLoai_PhanCap_TieuChi" Member="PhanCap_TieuChis" ThisKey="PhanLoai1" OtherKey="PhanLoai" Type="PhanCap_TieuChi" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuDangKy_DeTai_NCKH" Member="PhieuDangKy_DeTai_NCKHs">
    <Type Name="PhieuDangKy_DeTai_NCKH">
      <Column Name="MaPDK_NCKH" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ma_GVHD1" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Ma_GVHD2" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="TenDeTai" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDK" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ND_DeTai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="PhieuDangKy_DeTai_NCKH_DeTai_NCKH" Member="DeTai_NCKHs" ThisKey="MaPDK_NCKH" OtherKey="MaPDK_NCKH" Type="DeTai_NCKH" />
      <Association Name="PhieuDangKy_DeTai_NCKH_KQ_DeTai_NCKH" Member="KQ_DeTai_NCKHs" ThisKey="MaPDK_NCKH" OtherKey="MaPDK_NCKH" Type="KQ_DeTai_NCKH" />
      <Association Name="CanBo_HuongDan_PhieuDangKy_DeTai_NCKH" Member="CanBo_HuongDan" ThisKey="Ma_GVHD2" OtherKey="MaGV" Type="CanBo_HuongDan" IsForeignKey="true" />
      <Association Name="CanBo_HuongDan_PhieuDangKy_DeTai_NCKH1" Member="CanBo_HuongDan1" ThisKey="Ma_GVHD1" OtherKey="MaGV" Type="CanBo_HuongDan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuDangKy_LHTT" Member="PhieuDangKy_LHTTs">
    <Type Name="PhieuDangKy_LHTT">
      <Column Name="MaPDK_LHTT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaMinhChung" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NamHoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MSSV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="PhieuDangKy_LHTT_KQ_danhgia_LHTT_SV" Member="KQ_danhgia_LHTT_SVs" ThisKey="MaPDK_LHTT" OtherKey="MaPDK_LHTT" Type="KQ_danhgia_LHTT_SV" />
      <Association Name="MinhChung_PhieuDangKy_LHTT" Member="MinhChung" ThisKey="MaMinhChung" OtherKey="MaMinhChung" Type="MinhChung" IsForeignKey="true" />
      <Association Name="SinhVien_PhieuDangKy_LHTT" Member="SinhVien" ThisKey="MSSV" OtherKey="MSSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuDangKy_SV5T" Member="PhieuDangKy_SV5Ts">
    <Type Name="PhieuDangKy_SV5T">
      <Column Name="MaPDK_SV5T" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaMinhChung" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MaCap" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="NamHoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MSSV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Association Name="PhieuDangKy_SV5T_KQ_danhgia_SV5T_SV" Member="KQ_danhgia_SV5T_SVs" ThisKey="MaPDK_SV5T" OtherKey="MaPDK_SV5T" Type="KQ_danhgia_SV5T_SV" />
      <Association Name="CapDanhHieu_PhieuDangKy_SV5T" Member="CapDanhHieu" ThisKey="MaCap" OtherKey="MaCap" Type="CapDanhHieu" IsForeignKey="true" />
      <Association Name="MinhChung_PhieuDangKy_SV5T" Member="MinhChung" ThisKey="MaMinhChung" OtherKey="MaMinhChung" Type="MinhChung" IsForeignKey="true" />
      <Association Name="SinhVien_PhieuDangKy_SV5T" Member="SinhVien" ThisKey="MSSV" OtherKey="MSSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="MSSV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Ho" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoiSinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChiCuTru" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DiaChiLienLac" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NgayKetNapDoan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayVaoDang_dubi_neuco" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayVaoDang_chinhthuc_neuco" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChucVuDoan_neuco" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="SinhVien_DeTai_NCKH" Member="DeTai_NCKHs" ThisKey="MSSV" OtherKey="MSSV" Type="DeTai_NCKH" />
      <Association Name="SinhVien_PDK_BaiBao_ThamLuan_NCKH" Member="PDK_BaiBao_ThamLuan_NCKHs" ThisKey="MSSV" OtherKey="MSSV" Type="PDK_BaiBao_ThamLuan_NCKH" />
      <Association Name="SinhVien_PhieuDangKy_LHTT" Member="PhieuDangKy_LHTTs" ThisKey="MSSV" OtherKey="MSSV" Type="PhieuDangKy_LHTT" />
      <Association Name="SinhVien_PhieuDangKy_SV5T" Member="PhieuDangKy_SV5Ts" ThisKey="MSSV" OtherKey="MSSV" Type="PhieuDangKy_SV5T" />
      <Association Name="Lop_SinhVien" Member="Lop" ThisKey="MaLop" OtherKey="MaLop" Type="Lop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan_ADMIN" Member="TaiKhoan_ADMINs">
    <Type Name="TaiKhoan_ADMIN">
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="TaiKhoan_ADMIN_KQ_DanhGiaND_LHTT_Admin" Member="KQ_DanhGiaND_LHTT_Admins" ThisKey="TaiKhoan" OtherKey="TaiKhoan" Type="KQ_DanhGiaND_LHTT_Admin" />
      <Association Name="TaiKhoan_ADMIN_KQ_DanhGiaND_SV5T_Admin" Member="KQ_DanhGiaND_SV5T_Admins" ThisKey="TaiKhoan" OtherKey="TaiKhoan" Type="KQ_DanhGiaND_SV5T_Admin" />
    </Type>
  </Table>
  <Table Name="dbo.ThamSo" Member="ThamSos">
    <Type Name="ThamSo">
      <Column Name="[Key]" Member="Key" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ThuocTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="GiaTri" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TieuChi" Member="TieuChis">
    <Type Name="TieuChi">
      <Column Name="Ma_NDTieuChi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTieuChi" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenNDTieuChi" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Diem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaPhanCap" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Association Name="TieuChi_KQ_danhgia_LHTT_SV" Member="KQ_danhgia_LHTT_SVs" ThisKey="Ma_NDTieuChi" OtherKey="Ma_NDTieuChi" Type="KQ_danhgia_LHTT_SV" />
      <Association Name="TieuChi_KQ_danhgia_SV5T_SV" Member="KQ_danhgia_SV5T_SVs" ThisKey="Ma_NDTieuChi" OtherKey="Ma_NDTieuChi" Type="KQ_danhgia_SV5T_SV" />
      <Association Name="PhanCap_TieuChi_TieuChi" Member="PhanCap_TieuChi" ThisKey="MaPhanCap" OtherKey="MaPhanCap" Type="PhanCap_TieuChi" IsForeignKey="true" />
      <Association Name="TieuChuan_TieuChi" Member="TieuChuan" ThisKey="MaTieuChi" OtherKey="MaTieuChi" Type="TieuChuan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TieuChuan" Member="TieuChuans">
    <Type Name="TieuChuan">
      <Column Name="MaTieuChi" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTieuChi" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="TieuChuan_TieuChi" Member="TieuChis" ThisKey="MaTieuChi" OtherKey="MaTieuChi" Type="TieuChi" />
    </Type>
  </Table>
  <Function Name="dbo.Add_Admin" Method="Add_Admin">
    <Parameter Name="TK" Parameter="tK" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="MK" Parameter="mK" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Saukhi_upminhchung" Method="Saukhi_upminhchung">
    <Parameter Name="MaPDK" Parameter="maPDK" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Ma_NDTC" Parameter="ma_NDTC" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Add_MinhChung" Method="Add_MinhChung">
    <Parameter Name="TenMinhChung" Parameter="tenMinhChung" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="URL" Parameter="uRL" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Add_TieuChi" Method="Add_TieuChi">
    <Parameter Name="MaTChi" Parameter="maTChi" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="TenTChi" Parameter="tenTChi" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Diem" Parameter="diem" Type="System.Double" DbType="Float" />
    <Parameter Name="MaPhanCap" Parameter="maPhanCap" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="MaTieuChuan" Parameter="maTieuChuan" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Change_Admin" Method="Change_Admin">
    <Parameter Name="TK" Parameter="tK" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="MK" Parameter="mK" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="MK_moi" Parameter="mK_moi" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Change_InfoSV" Method="Change_InfoSV">
    <Parameter Name="MSSV" Parameter="mSSV" Type="System.String" DbType="Char(10)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="SDT_moi" Parameter="sDT_moi" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="QueQuan_moi" Parameter="queQuan_moi" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="GioiTinh_moi" Parameter="gioiTinh_moi" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Email_moi" Parameter="email_moi" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NoiSinh_moi" Parameter="noiSinh_moi" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DiaChiCuTru_moi" Parameter="diaChiCuTru_moi" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="DiaChiLienLac_moi" Parameter="diaChiLienLac_moi" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="NgayKetDoan_moi" Parameter="ngayKetDoan_moi" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="NgayVaoDang_dubi_moi" Parameter="ngayVaoDang_dubi_moi" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="NgayVaoDang_chinhthuc_moi" Parameter="ngayVaoDang_chinhthuc_moi" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ChucVuDoan_moi" Parameter="chucVuDoan_moi" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Change_passSV" Method="Change_passSV">
    <Parameter Name="MSSV" Parameter="mSSV" Type="System.String" DbType="Char(10)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="pass_moi" Type="System.String" DbType="NVarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Change_TieuChi" Method="Change_TieuChi">
    <Parameter Name="MaTChi" Parameter="maTChi" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="MaTChi_Moi" Parameter="maTChi_Moi" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="TenTChi_Moi" Parameter="tenTChi_Moi" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Diem_Moi" Parameter="diem_Moi" Type="System.Double" DbType="Float" />
    <Parameter Name="MaPhanCap_Moi" Parameter="maPhanCap_Moi" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="MaTieuChuan_Moi" Parameter="maTieuChuan_Moi" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Del_Admin" Method="Del_Admin">
    <Parameter Name="TK" Parameter="tK" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Del_TieuChi" Method="Del_TieuChi">
    <Parameter Name="MaTChi" Parameter="maTChi" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Del_TieuChuan" Method="Del_TieuChuan">
    <Parameter Name="MaTChuan" Parameter="maTChuan" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="TenTChuan" Parameter="tenTChuan" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DKy_DSachSV_NCKH" Method="DKy_DSachSV_NCKH">
    <Parameter Name="MaPDK_NCKH" Parameter="maPDK_NCKH" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="MSSV_SV1" Parameter="mSSV_SV1" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MSSV_SV2" Parameter="mSSV_SV2" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MSSV_SV3" Parameter="mSSV_SV3" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DKy_LHTT" Method="DKy_LHTT">
    <Parameter Name="MaMinhChung" Parameter="maMinhChung" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="NamHoc" Parameter="namHoc" Type="System.Int32" DbType="Int" />
    <Parameter Name="MSSV" Parameter="mSSV" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DKy_NCKH" Method="DKy_NCKH">
    <Parameter Name="Ma_GVHD1" Parameter="ma_GVHD1" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="Ma_GVHD2" Parameter="ma_GVHD2" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="TenDeTai" Parameter="tenDeTai" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="NgayDK" Parameter="ngayDK" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ND_DeTai" Parameter="nD_DeTai" Type="System.String" DbType="NVarChar(200)" />
    <ElementType Name="DKy_NCKHResult">
      <Column Name="MaPDK" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DKy_NCKH_2" Method="DKy_NCKH_2">
    <Parameter Name="MSSV" Parameter="mSSV" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MaPDK_NCKH" Parameter="maPDK_NCKH" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DKy_SV5T" Method="DKy_SV5T">
    <Parameter Name="MaMinhChung" Parameter="maMinhChung" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="MaCap" Parameter="maCap" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="NamHoc" Parameter="namHoc" Type="System.Int32" DbType="Int" />
    <Parameter Name="MSSV" Parameter="mSSV" Type="System.String" DbType="Char(10)" />
    <ElementType Name="DKy_SV5TResult">
      <Column Name="MaPDK" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DKy_SV5T_2" Method="DKy_SV5T_2">
    <Parameter Name="MaPDK_SV5T" Parameter="maPDK_SV5T" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Ma_ND" Parameter="ma_ND" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetInfoSV" Method="GetInfoSV">
    <Parameter Name="MSSV" Parameter="mSSV" Type="System.String" DbType="Char(10)" />
    <ElementType Name="GetInfoSVResult">
      <Column Name="MSSV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaLop" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Ho" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoiSinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChiCuTru" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DiaChiLienLac" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NgayKetNapDoan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayVaoDang_dubi_neuco" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayVaoDang_chinhthuc_neuco" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChucVuDoan_neuco" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTaiLieu_LHTT" Method="GetTaiLieu_LHTT">
    <ElementType Name="GetTaiLieu_LHTTResult">
      <Column Name="Ma_NDTieuChi" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaTieuChi" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenNDTieuChi" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Diem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaPhanCap" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTaiLieu_SV5T_TheoCap" Method="GetTaiLieu_SV5T_TheoCap">
    <Parameter Name="MaCap" Parameter="maCap" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="GetTaiLieu_SV5T_TheoCapResult">
      <Column Name="Ma_NDTieuChi" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaTieuChi" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenNDTieuChi" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Diem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaPhanCap" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTieuChiSV5T_TheoMSSV_TheoCap" Method="GetTieuChiSV5T_TheoMSSV_TheoCap">
    <Parameter Name="MSSV" Parameter="mSSV" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="MaCap" Parameter="maCap" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="GetTieuChiSV5T_TheoMSSV_TheoCapResult">
      <Column Name="MaPDK_SV5T" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MaMinhChung" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MaCap" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="NamHoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MSSV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Ma_NDTieuChi" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaTieuChi" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenNDTieuChi" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Diem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaPhanCap" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Ma_NDTieuChi1" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaPDK_SV5T1" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Login_Acc" Method="Login_Acc">
    <Parameter Name="MSSV" Parameter="mSSV" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="Login_AccResult">
      <Column Name="MSSV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.DsachDK_SV5T_Lop" Method="DsachDK_SV5T_Lop">
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="MaCap" Parameter="maCap" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="DsachDK_SV5T_LopResult">
      <Column Name="Ho" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MSSV" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>